//! M15 torture suite against the checked-in raw-GPS fixtures
//! (`tests/fixtures/*.json`, regenerated by `--example generate_fixtures`).
//!
//! Each fixture is a schema-versioned document (`schema_version: 1`); the
//! parser also accepts legacy versionless files. The generator embeds each
//! fixture's canonical route; the invariants here
//! hold regardless of fixture content, so the suite still passes if someone
//! regenerates the files with a different seed:
//!
//! - processing never fails, never panics, and audits *every* raw fix;
//! - the accepted count agrees with the cleaned track length exactly;
//! - the cleaned track is a valid chronological route;
//! - every accepted fix lies within a lateral corridor of its route;
//! - the out-and-back fixture is matched with continuity and no re-anchors.

use std::fs;

use gps_engine::geo::project_to_polyline;
use gps_engine::gps::Fixture;
use gps_engine::route::ContinuityConfig;
use gps_engine::track::FilterConfig;

fn fixture(name: &str) -> Fixture {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    Fixture::from_json(&fs::read_to_string(&path).expect("fixture exists")).expect("fixture parses")
}

fn check_fixture(name: &str, corridor_m: f64) {
    let fixture = fixture(name);
    let route = fixture.route.as_ref().expect("fixture embeds its route");
    let geometry = route.geometry();
    let trace = &fixture.trace;
    let processed = trace
        .process(&FilterConfig::default())
        .expect("processing succeeds");

    assert_eq!(
        processed.samples.len(),
        trace.len(),
        "one decision per raw fix"
    );
    assert_eq!(
        processed.accepted(),
        processed.track.points().len(),
        "accepted count must equal the cleaned track length"
    );
    assert!(processed.accepted() >= 2, "usable track survives");
    assert!(
        processed
            .track
            .points()
            .windows(2)
            .all(|w| { w[1].timestamp().unix_ms() >= w[0].timestamp().unix_ms() }),
        "cleaned track timestamps are chronological"
    );

    for sample in &processed.samples {
        if !sample.accepted {
            let reason = sample.reason.expect("rejected samples carry a reason");
            assert!(!reason.to_string().is_empty());
        }
    }

    // Every *accepted* fix must stay inside the route corridor. (The corridor
    // is deliberately wide: it must hold even against a regenerated seed.)
    for point in processed.track.points() {
        let projection =
            project_to_polyline(point.coordinate(), geometry).expect("route non-empty");
        assert!(
            projection.lateral_error.meters() <= corridor_m,
            "{name}: accepted point {:?} is {} m off the route (corridor {corridor_m} m)",
            point.coordinate(),
            projection.lateral_error.meters(),
        );
    }
}

#[test]
fn clean_loop_stays_on_route() {
    check_fixture("clean_loop.json", 20.0);
    let fixture = fixture("clean_loop.json");
    let processed = fixture.trace.process(&FilterConfig::default()).unwrap();
    assert_eq!(
        processed.accepted(),
        fixture.trace.len(),
        "a clean trace loses nothing"
    );
    assert!(
        processed
            .samples
            .iter()
            .any(|s| matches!(s.quality, gps_engine::gps::GpsQuality::Good)),
        "clean fixes are graded good"
    );
}

#[test]
fn out_and_back_stays_on_route() {
    check_fixture("out_and_back.json", 20.0);
    let fixture = fixture("out_and_back.json");
    let processed = fixture.trace.process(&FilterConfig::default()).unwrap();
    assert_eq!(processed.accepted(), fixture.trace.len());
    assert_eq!(processed.rejected(), 0);
}

#[test]
fn gps_jitter_is_graded_degraded_but_accepted_is_usable() {
    let fixture = fixture("gps_jitter.json");
    let processed = fixture.trace.process(&FilterConfig::default()).unwrap();
    check_fixture("gps_jitter.json", 40.0);
    assert!(
        processed
            .samples
            .iter()
            .any(|s| matches!(s.quality, gps_engine::gps::GpsQuality::Degraded)),
        "jittered fixes report degraded accuracy (14 m > 12 m good threshold)"
    );
    assert!(
        processed.accepted() * 100 >= processed.samples.len() * 60,
        "jitter mostly survives"
    );
}

#[test]
fn gps_jump_drops_the_outliers() {
    let fixture = fixture("gps_jump.json");
    let processed = fixture.trace.process(&FilterConfig::default()).unwrap();
    check_fixture("gps_jump.json", 40.0);
    assert!(processed.rejected() > 0, "jumping fixes must be rejected");
}

#[test]
fn gps_dropout_recovers_across_gaps() {
    check_fixture("gps_dropout.json", 20.0);
    let fixture = fixture("gps_dropout.json");
    let trace = &fixture.trace;
    let processed = trace.process(&FilterConfig::default()).unwrap();
    // A quarter of samples were dropped at generation: the *raw* trace is
    // sparser than the clean one, but the cleaned track still spans the route.
    assert!(processed.track.points().len() >= 2);
    assert!(
        processed.track.distance().meters() > 0.0,
        "surviving fixes cover real distance"
    );
}

#[test]
fn out_and_back_matches_with_continuity() {
    let fixture = fixture("out_and_back.json");
    let route = fixture.route.clone().expect("embedded route");
    let track = fixture.trace.to_track().expect("trace builds a track");
    let series = route.project_track_with_continuity(&track, &ContinuityConfig::default());

    let total = route.length().meters();
    let last = series.last().expect("non-empty series");
    assert!(
        (last.distance.meters() - total).abs() <= 200.0,
        "continuity coverage reaches the far end: {} of {total} m",
        last.distance.meters()
    );
    assert_eq!(
        series.iter().filter(|p| p.reanchored).count(),
        0,
        "no global re-anchoring"
    );
    assert_eq!(
        series.iter().filter(|p| p.backtracker).count(),
        0,
        "no backtracking on a clean run"
    );
}

#[test]
fn all_fixtures_reverse_is_stable() {
    // Serialization must be idempotent: re-parsing a serialized fixture yields
    // exactly the same document again. (Struct equality is deliberately not
    // asserted: a bearing's `as_degrees`/`from_degrees` pair loses ulps of
    // float precision, so equal JSON is the meaningful round-trip contract.)
    for name in [
        "clean_loop.json",
        "gps_jitter.json",
        "gps_jump.json",
        "gps_dropout.json",
        "out_and_back.json",
    ] {
        let f = fixture(name);
        let first = f.to_json();
        let reparsed = Fixture::from_json(&first).expect("to_json round-trips");
        assert_eq!(reparsed.to_json(), first, "round-trip stable for {name}");
    }
}
